project:
  type: website

website:
  title: "My Explorations with LLMs in Social Contexts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ezou626
      - icon: twitter
        href: https://x.com/EDubsZ123
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


